# Prometheus Configuration for NanoARB

global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    monitor: 'nanoarb'

scrape_configs:
  # NanoARB Trading Engine
  - job_name: 'nanoarb'
    static_configs:
      - targets: ['host.docker.internal:9090']  # Access host machine from Docker
    scrape_interval: 1s
    metrics_path: /metrics

